# Generated by Django 5.0.4 on 2024-04-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_active_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRating',
        ),
    ]
