# Generated by Django 5.0.4 on 2024-04-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_delete_courserating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
